version: "3.6"
services:
  prod:
    image: tons/hello-db:${IMAGE_TAG:-latest}
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database

  dev:
    build:
      context: .
      target: build
    env_file:
      - .env
    volumes:
      - .:/src
    working_dir: /src
    ports:
      - "8080:8080"
    command: reflex -r "Dockerfile|\.go|\.yml$$" -s -- sh -c "go run ."

  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
