services:
  dev:
    build:
      context: .
      target: build
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - .:/src
    working_dir: /src
    command: go run .
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git
            - .idea
            - README.md
            - Makefile
    depends_on:
      database:
        condition: service_healthy
